spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaob26y909x9N5Vh5d7
            client-secret: dTuQbizupJHMSPytuXoAn3JYA5MAYYhYWBnrI9YCt6ofNc8CcOuT354GSXSReLzr
        provider:
          okta:
            authorization-uri: https://dev-56694765.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-56694765.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-56694765.okta.com/oauth2/default/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-56694765.okta.com/oauth2/default/v1/keys
